export const DatabaseData = [
    {
        id: "1",
        date: "Jan 26",
        team1: "Leafs",
        team2: "Senators",
        betType: "Moneyline",
        odds1: "1.9",
        bet1: "100",
        party1: "Tristan",
        sportsbook1: "Bet365",
        odds2: "1.9",
        bet2: "100",
        party2: "Tristan",
        sportsbook2: "Betway",
        winner: "Tristan",
        payout: "190",
        pAndL: "-10",
        verify: "-1",
        className: "example1"
    },
    {
        id: "2",
        date: "Input1",
        team1: "Input1",
        team2: "Input1",
        betType: "Input1",
        odds1: "Input1",
        bet1: "Input1",
        party1: "Input1",
        sportsbook1: "Input1",
        odds2: "Input1",
        bet2: "Input1",
        party2: "Input1",
        sportsbook2: "Input1",
        winner: "Input2",
        payout: "Input2",
        pAndL: "Input2",
        verify: "Input3",
        className: "example2"
    },
    {
        id: "3",
        date: "Input1",
        team1: "Input1",
        team2: "Input1",
        betType: "Input1",
        odds1: "Input1",
        bet1: "Input1",
        party1: "Input1",
        sportsbook1: "Input1",
        odds2: "Input1",
        bet2: "Input1",
        party2: "Input1",
        sportsbook2: "Input1",
        winner: "Input2",
        payout: "Input2",
        pAndL: "Input2",
        verify: "Input3",
        className: "example3"
    },
    {
        id: "4",
        date: "Input1",
        team1: "Input1",
        team2: "Input1",
        betType: "Input1",
        odds1: "Input1",
        bet1: "Input1",
        party1: "Input1",
        sportsbook1: "Input1",
        odds2: "Input1",
        bet2: "Input1",
        party2: "Input1",
        sportsbook2: "Input1",
        winner: "Input2",
        payout: "Input2",
        pAndL: "Input2",
        verify: "Input3",
        className: "example4"
    },
]